print("Welcome to The Tip Calculator.")
bill=float(input("what was the totle bill ? $"))
tip=int(input("what percentage tip would you like to give 10 , 12 or 15 ?"))
people=int(input("how many people to split the bill ?"))
tip=float(tip/100)
tip=float(bill*tip)
pay=float((bill+tip)/people)
pay=round(pay,2)
print("Each person should pay: $",pay)